[package]
name = "risemode-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = { version = "2.6", default-features = false, features = ["linux-shared-hidraw"] }
anyhow = "1.0"
sysinfo = "0.31"
